baseurl = "https://agnesdjafri.com/"
title = "Agnes Djafri"
theme = "hugo-creative-portfolio-theme"
languageCode = "fr"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "violet"
  description = "Agnes Djafri - Art Portfolio"
  copyright = "&copy;2019 Agnes Djafri"
  sidebarAbout = [
    "Participe à la <a href="poolartfair.com" target="_blank">Pool Art Fair 2010</a> !",<a href="poolartfair.com" target="_blank">Pool Art Fair 2020</a>
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "contact@agnesdjafri.com"


  # Nav links in the side bar
  [[params.navlinks]]
  name = "Portfolio"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Biographie"
  url = "about/"

  [[params.navlinks]]
  name = "Pool Art Fair 2020"
  url = "actus/"

 # [[params.navlinks]]
 # name = "Press"
 # url = "press/"

  [[params.navlinks]]
  name = "Contact"
  url = "contact/"

  [params.social]
  instagram     = "https://www.instagram.com/agnesdjafri/"
  whatsapp      = "https://wa.me/590690502805"
  facebook      = "facebook.com/agnesdjafriart"
  email         = "contact@agnesdjafri.com"