backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
site_url: https://agnesdjafri.com
display_url: https://agnesdjafri.com
logo_url: https://agnesdjafri.com/img/logo.png
media_folder: static/img/uploads
public_folder: /img/uploads
collections:
  - label: "Tableau"
    name: "artpiece"
    folder: "content/portfolio"
    create: true
    slug: "{{year}}{{slug}}"
    filter: {field: "pieceType", value: "art"}
    editor:
      preview: true
    fields:
      - {label: "Brouillon", name: "draft", widget: "hidden", default: false, hint: "Une page en brouillon (signalé en bleu) ne se pas visible sur le site"}
      - {label: "LayoutType", name: "pieceType", widget: "hidden",  default: "art"}
      - {label: "Titre", name: "title", widget: "string" }
      - {label: "Série", name: "serie", widget: "string", required: false}
      - {label: "ShowImage", name: "showonlyimage", widget: "hidden",  default: true}
      - {label: "Image", name: "image",  widget: "image"}
      - {label: "Corps de page", name: "body", widget: "markdown", required: false}
      #     - label: "Infos"
      #       name: "data"
      #       widget: "object"
      #       fields:
      #         - {label: "Hauteur", name: "height", widget: "number", valueType: "int", required: false}
      #         - {label: "Largeur", name: "width", widget: "number", valueType: "int", required: false}
      #         - {label: "Année", name: "year", widget: "datetime", default: "", dateFormat: "YYYY", format: "L", required: false}
      #         - {label: "Techniques", name: "technics", widget: "list", required: false}
      #         - {label: "Mention Vendu", name: "sold", widget: "boolean",  default: false, required: false}
      #         - {label: "Prix", name: "price", widget: "number", valueType: "int", required: false}  
  - label: "Texte"
    name: "textpiece"
    folder: "content/portfolio"
    create: true
    slug: "{{year}}{{slug}}"
    filter: {field: "pieceType", value: "text"}
    editor:
      preview: true
    fields:
      - {label: "Brouillon", name: "draft", widget: "hidden", default: false, hint: "Une page en brouillon (signalé en bleu) ne se pas visible sur le site"}
      - {label: "LayoutType", name: "pieceType", widget: "hidden",  default: "text"}
      - {label: "Titre", name: "title", widget: "string" }
      - {label: "Série", name: "serie", widget: "string", required: false}
      - {label: "NoImage", name: "showonlyimage", widget: "hidden",  default: false}
      - {label: "Corps de page", name: "body", widget: "markdown", required: false }
  - label: "Page (WIP)"
    name: "page"
    folder: "content/actus"
    create: true
    slug: "{{year}}{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Brouillon", name: "draft", widget: "hidden", default: false, hint: "Une page en brouillon (signalé en bleu) ne se pas visible sur le site"}
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Corps de page", name: "body", widget: "markdown", required: false }
  - label: "Pages menu"
    name: "pages"
    files:
      - file: "content/about/_index.md"
        label: "Biographie"
        name: "bio"
        fields:
          - {label: "Brouillon", name: "draft", widget: "boolean", default: false, hint: "Une page en brouillon (signalé en bleu) ne se pas visible sur le site"}
          - {label: "Titre", name: title, widget: string}
          - {label: "Corps de texte", name: body, widget: markdown, required: false}
      - file: "content/contact/_index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Brouillon", name: "draft", widget: "boolean", default: false, hint: "Une page en brouillon (signalé en bleu) ne se pas visible sur le site"}
          - {label: "Titre", name: title, widget: string}
          - {label: "Corps de texte", name: body, widget: markdown, required: false}
      