backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
site_url: https://agnesdjafri.com
display_url: https://agnesdjafri.com
logo_url: https://agnesdjafri.com/img/logo.png
media_folder: static/img/uploads
public_folder: /img/uploads
collections:
  - label: "Tableau"
    name: "artpiece"
    folder: "content/portfolio"
    create: true
    slug: "{{year}}{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Brouillon", name: "draft", widget: "boolean", default: true}
      - {label: "Titre", name: "title", widget: "string" }
      - {label: "Série", name: "serie", widget: "string"}
      - {label: "Image", name: "image",  widget: "image",  default: "/uploads/placeholder.jpg"}
      - label: "Dimensions"
        name: "dimensions"
        widget: "object"
        fields:
          - {label: "Hauteur", name: "height", widget: "number", valueType: "int"}
          - {label: "Largeur", name: "width", widget: "number", valueType: "int"}
      - {label: "Techniques", name: "technics", widget: "list"}
      - {label: "Année", name: "year", widget: "datetime", default: "", dateFormat: "YYYY", format: "L"}
      - {label: "Mention Vendu", name: "sold", widget: "boolean",  default: false}
      - {label: "Prix", name: "price", widget: "number", valueType: "int"}
      - {label: "Corps de page", name: "body", widget: "markdown" }
  - label: "Texte"
    name: "textpiece"
    folder: "content/portfolio"
    create: true
    slug: "{{year}}{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Brouillon", name: "draft", widget: "boolean", default: true}
      - {label: "Titre", name: "title", widget: "string" }
      - {label: "Série", name: "serie", widget: "string"}
      - {label: "TextPiece", name: "showonlyimage", widget: "hidden",  default: false}
      - {label: "Corps de page", name: "body", widget: "markdown" }
  - label: "Page (WIP)"
    name: "page"
    folder: "content/actus"
    create: true
    slug: "{{year}}{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Brouillon", name: "draft", widget: "boolean", default: true}
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Corps de page", name: "body", widget: "markdown" }
  - label: "Pages menu"
    name: "pages"
    files:
      - file: "content/about/_index.md"
        label: "Biographie"
        name: "bio"
        fields:
          - {label: "Brouillon", name: "draft", widget: "boolean", default: true}
          - {label: "Titre", name: title, widget: string}
          - {label: "Corps de texte", name: body, widget: markdown}
      - file: "content/contact/_index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Brouillon", name: "draft", widget: "boolean", default: true}
          - {label: "Titre", name: title, widget: string}
          - {label: "Corps de texte", name: body, widget: markdown}
      